# Setup env
FROM node:10-buster-slim
RUN mkdir -p /app
WORKDIR /app
RUN apt update
# For deasync@0.1.14
RUN apt install -y python build-essential
# For gatsby-plugin-sharp@2.2.28
RUN apt install -y libvips

# Setup app
COPY package.json .
COPY package-lock.json .
RUN npm install

# Add app
COPY gatsby-browser.js .
COPY gatsby-config.js .
COPY gatsby-node.js .
COPY tsconfig.json .
COPY src src

# Run app
CMD npm run dev