#!/bin/sh

set -e

# Go
if [ "$1" = "go" ]; then
    # Install native dependencies
    apt update
    apt install -y curl make npm

    # Install bagop
    curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
    install /tmp/bagop /usr/local/bin

    # Generate dependencies
    make depend

    # Build
    CGO_ENABLED=0 bagop -j "$(nproc)" -b "$2" -x '(android/*|ios/*)' -p "make build-cli/$2 DST=\$DST" -d out

    exit 0
fi

# Frontend
if [ "$1" = "pwa" ]; then
    # Install Hugo
    apk add curl make hugo npm

    # Generate dependencies
    make depend

    # Build
    make build-pwa/ps-pwa

    exit 0
fi
